### ISSUE TITLE
Command not found error

### ISSUE THREAD

**Issue by vduggal999** [Kevin-De-Koninck/pi-hole-helpers#1]
Hi there,

I'm getting a command not found error when running pihole-helper.sh. Everything installed correctly but it won't run.

Thanks,
V

**Comment by Kevin-De-Koninck** [comment]
Which command?

PS: sorry for the really late reply

**Comment by Mikez333** [comment]
same thing for me. I ran sudo pihole-helper and it said command not found

**Comment by Mikez333** [comment]
oh i figured it out. Type cd /opt/pihole and then "sudo bash pihole-helper.sh"
